// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKLIOvi9WpTHj8cR723tioM2Uj9kqAqng',
    appId: '1:331198290666:web:80981b38035c6a7edd1593',
    messagingSenderId: '331198290666',
    projectId: 'flutter-firebase-udemy-example',
    authDomain: 'flutter-firebase-udemy-example.firebaseapp.com',
    storageBucket: 'flutter-firebase-udemy-example.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDkHrQQPt44j6_iLwdkJ_Irak2W0erCrU',
    appId: '1:331198290666:android:28cb3cba834419dddd1593',
    messagingSenderId: '331198290666',
    projectId: 'flutter-firebase-udemy-example',
    storageBucket: 'flutter-firebase-udemy-example.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWYexknaOR7_IRbd4eZyswglsUlPjQewI',
    appId: '1:331198290666:ios:0318f29b0210e541dd1593',
    messagingSenderId: '331198290666',
    projectId: 'flutter-firebase-udemy-example',
    storageBucket: 'flutter-firebase-udemy-example.appspot.com',
    androidClientId: '331198290666-283qj9dlsar7rp80trfptef4cpu9pvbt.apps.googleusercontent.com',
    iosClientId: '331198290666-sem5om3lonf3blt8a8iujmvdm9q6t7gu.apps.googleusercontent.com',
    iosBundleId: 'com.example.messageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWYexknaOR7_IRbd4eZyswglsUlPjQewI',
    appId: '1:331198290666:ios:0318f29b0210e541dd1593',
    messagingSenderId: '331198290666',
    projectId: 'flutter-firebase-udemy-example',
    storageBucket: 'flutter-firebase-udemy-example.appspot.com',
    androidClientId: '331198290666-283qj9dlsar7rp80trfptef4cpu9pvbt.apps.googleusercontent.com',
    iosClientId: '331198290666-sem5om3lonf3blt8a8iujmvdm9q6t7gu.apps.googleusercontent.com',
    iosBundleId: 'com.example.messageApp',
  );
}
